alias: Sync ST Switch and Amelia's Lamp Sonoff
trigger:
  - platform: state
    entity_id: light.amelias_lamp_st
  - platform: state
    entity_id: light.amelias_lamp
action:
  - service_template: "light.turn_{{ trigger.to_state.state }}"
    data_template:
      entity_id: >-
        {% if trigger.entity_id == 'light.amelias_lamp_st' %}
          light.amelias_lamp
        {% else %}
          light.amelias_lamp_st
        {% endif %}
