alias: Turn on the light for Jeff
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.sliding_door
  to: 'on'
condition:
  condition: state
  entity_id: sun.sun
  state: 'below_horizon'
action:
  service: light.turn_on
  entity_id: light.deck_lights

