alias: Sync ST Switch and Living Room Lamp Sonoff
trigger:
  - platform: state
    entity_id: light.living_room_lamp_st
  - platform: state
    entity_id: light.living_room_lamp
action:
  - service_template: "light.turn_{{ trigger.to_state.state }}"
    data_template:
      entity_id: >-
        {% if trigger.entity_id == 'light.living_room_lamp_st' %}
          light.living_room_lamp
        {% else %}
          light.living_room_lamp_st
        {% endif %}
