alias: Sync ST Switch and Office Lamp Sonoff
trigger:
  - platform: state
    entity_id: light.office_lamp_st
  - platform: state
    entity_id: light.office_lamp
action:
  - service_template: "light.turn_{{ trigger.to_state.state }}"
    data_template:
      entity_id: >-
        {% if trigger.entity_id == 'light.office_lamp_st' %}
          light.office_lamp
        {% else %}
          light.office_lamp_st
        {% endif %}
