homeassistant:
  # Name of the location where Home Assistant is running
  name: noisufnocHome
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Includes
alarm_control_panel: !include alarm_control_panel.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml
remote: !include remote.yaml
notify: !include notify.yaml
logger: !include logger.yaml

# Enables
updater:
discovery:
conversation:
history:
logbook:
sun:

# Things that didnt get put into an included yaml file...
        
# Text to speech
tts:
  platform: google

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

ifttt:
  key: !secret ifttt_key

# https://home-assistant.io/blog/2016/02/09/Smarter-Smart-Things-with-MQTT-and-Home-Assistant/    
mqtt:
  broker: localhost
