homeassistant:
  name: noisufnoc
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret elevation
  time_zone: America/New_York
  unit_system: imperial
  customize: !include customize.yaml
  packages: !include_dir_named packages/

# Enables the frontend
frontend:

recorder:
  db_url: !secret recorder_db_url

http:
  api_password: !secret api_password
  use_x_forwarded_for: True
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Includes
alarm_control_panel: !include alarm_control_panel.yaml
binary_sensor: !include_dir_list binary_sensors/
sensor: !include_dir_list sensors/
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
script: !include_dir_merge_named script/
light: !include_dir_list lights/
switch: !include_dir_list switches/
remote: !include remote.yaml
notify: !include notify.yaml
logger: !include logger.yaml
camera: !include camera.yaml
zone: !include_dir_list zone/
automation: !include_dir_list automations/
input_select: !include input_select.yaml

# Enables
updater:
discovery:
conversation:
history:
logbook:
sun:
config:

# Things that didnt get put into an included yaml file...
        
# Text to speech
tts:
  platform: google

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

ifttt:
  key: !secret ifttt_key

# https://home-assistant.io/blog/2016/02/09/Smarter-Smart-Things-with-MQTT-and-Home-Assistant/    
mqtt:
  broker: localhost

splunk:
  token: !secret splunk_token
  host: hec.noisufnoc.net

apcupsd:
  host: apcupsd.noisufnoc.net

#apiai:
#intent_script: !include intent_script.yaml

usps:
  username: !secret usps_username
  password: !secret usps_password

google_assistant:
  project_id: !secret google_project_id
  client_id: !secret google_client_id
  access_token: !secret google_access_token
  expose_by_default: true
  #  entity_config:
  #  switch.roomba:
  #    name: Roomba
#      aliases:
#        - bright lights
#        - entry lights
#    light.living_room:
#      expose: false
#      room: living room

