homeassistant:
  # Name of the location where Home Assistant is running
  name: noisufnoc
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include customize.yaml

# Enables the frontend
frontend:

http:
  api_password: !secret api_password
  use_x_forwarded_for: True
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Includes
alarm_control_panel: !include alarm_control_panel.yaml
binary_sensor: !include_dir_list binary_sensors/
sensor: !include_dir_list sensors/
device_tracker: !include device_tracker.yaml
group: !include_dir_merge_named group/
script: !include_dir_merge_named script/
light: !include_dir_list lights/
remote: !include remote.yaml
notify: !include notify.yaml
logger: !include logger.yaml
camera: !include camera.yaml
zone: !include_dir_list zone/
automation: !include_dir_list automations/

# Enables
updater:
discovery:
conversation:
history:
logbook:
sun:
config:

# Things that didnt get put into an included yaml file...
        
# Text to speech
tts:
  platform: google

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

ifttt:
  key: !secret ifttt_key

# https://home-assistant.io/blog/2016/02/09/Smarter-Smart-Things-with-MQTT-and-Home-Assistant/    
mqtt:
  broker: localhost

splunk:
  token: !secret splunk_token
  host: fwd01.noisufnoc.net
