- platform: pushbullet
  name: Pushbullet
  api_key: !secret pushbullet_api_key

- platform: pushover
  name: Pushover
  api_key: !secret pushover_api_key
  user_key: !secret pushover_user_key

- platform: html5
  name: Chrome
  gcm_api_key: !secret html5_gcm_api_key
  gcm_sender_id: !secret html5_gcm_sender_id

