# Weather Prediction
- platform: wunderground
  api_key: !secret wunderground_api
  monitored_conditions:
    - alerts
    - dewpoint_c
    - dewpoint_f
    - dewpoint_string
    - feelslike_c
    - feelslike_f
    - feelslike_string
    - heat_index_c
    - heat_index_f
    - heat_index_string
    - elevation
    - location
    - observation_time
    - precip_1hr_in
    - precip_1hr_metric
    - precip_1hr_string
    - precip_today_in
    - precip_today_metric
    - precip_today_string
    - pressure_in
    - pressure_mb
    - pressure_trend
    - relative_humidity
    - station_id
    - solarradiation
    - temperature_string
    - temp_c
    - temp_f
    - UV
    - visibility_km
    - visibility_mi
    - weather
    - wind_degrees
    - wind_dir
    - wind_gust_kph
    - wind_gust_mph
    - wind_kph
    - wind_mph
    - wind_string

# Plex Activity Monitor
- platform: plex
  host: plex.noisufnoc.net
  username: noisufnoc
  password: !secret plex_password

# SABnzbd
- platform: sabnzbd
  host: tv.noisufnoc.net
  api_key: !secret sabnzbd_api_key
  monitored_variables:
    - 'current_status'
    - 'speed'
    - 'queue_size'
    - 'queue_remaining'
    - 'disk_size'
    - 'disk_free'

# Speedtest.net
- platform: speedtest
  server_id: !secret speedtest_server_id
  monitored_conditions:
    - ping
    - download
    - upload

# ST Door Temp
- platform: mqtt
  state_topic: "smartthings/Sliding Glass Door/temperature"
  name: "Glass Door Temp"
  unit_of_measurement: "°F"
