- platform: mqtt
  name: "Family Room Light"
  state_topic: "smartthings/Family Room Light/switch"
  command_topic: "smartthings/Family Room Light/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true
