alias: 'Minimote A Button 3 - Pressed'
trigger:
  platform: mqtt
  topic: smartthings/minimote a/button
  payload: '{"button": 3, "action": "pushed"}'
action:
  service: tts.google_say
  entity_id: media_player.kitchen_home
  data_template:
    message: >
        Steven Pressed The Button!
