alias: 'Minimote A Button 2 - Pressed'
trigger:
  platform: mqtt
  topic: smartthings/minimote a/button
  payload: '{"button": 2, "action": "pushed"}'
action:
  service: light.turn_off
  data:
    entity_id: light.family_room_lamp
