alias: 'Minimote B: Button 1 - Pressed'
trigger:
  platform: mqtt
  topic: smartthings/minimote b/button
  payload: '{"button": 1, "action": "pushed"}'
action:
  service: light.toggle
  data:
    entity_id: light.ashleys_nightstand
