alias: 'Minimote B: Button 3 - Pressed'
trigger:
  platform: mqtt
  topic: smartthings/minimote b/button
  payload: '{"button": 3, "action": "pushed"}'
action:
  service: light.toggle
  data:
    entity_id:
      - light.ashleys_nightstand
      - light.mikes_nightstand
