alias: 'Minimote B: Button 2 - Pressed'
trigger:
  platform: mqtt
  topic: smartthings/minimote b/button
  payload: '{"button": 2, "action": "pushed"}'
action:
  service: light.toggle
  data:
    entity_id: light.mikes_nightstand
