alias: 'Minimote Button 1 Press'
trigger:
  platform: mqtt
  topic: smartthings/Kyse's Aeon Minimote/button
  payload: '{"button": 1, "action": "pushed"}'
action:
  service: light.turn_on
  data:
    entity_id: light.family_room_lamp
