alias: 'Minimote Button 2 Press'
trigger:
  platform: mqtt
  topic: smartthings/Kyse's Aeon Minimote/button
  payload: '{"button": 2, "action": "pushed"}'
action:
  service: light.turn_off
  data:
    entity_id: light.family_room_lamp
