alias: 'Minimote Button 1 Held'
trigger:
  platform: mqtt
  topic: smartthings/Kyse's Aeon Minimote/button
  payload: '{"button": 1, "action": "held"}'
action:
  service: light.toggle
  data:
    entity_id: light.family_room_lamp
