alias: 'Minimote Button 4 Press'
trigger:
  platform: mqtt
  topic: smartthings/Kyse's Aeon Minimote/button
  payload: '{"button": 4, "action": "pushed"}'
action:
  service: tts.google_say
  entity_id: media_player.kitchen_home
  data_template:
    message: >
        Don't push the button!
