alias: 'Notify if any exterior door open past midnight'
trigger:
  platform: time
  at: '00:00:00'
condition:
  condition: state
  entity_id: 'group.exterior_doors'
  state: 'on'
action:
  - service: notify.chrome_motox
      data:
        message: 'You left a door open!'
