alias: 'Notify if any exterior door open past midnight'
trigger:
  platform: time
  at: '22:00:00'
condition:
  condition: state
  entity_id: 'group.interior_doors'
  state: 'on'
action:
  service: notify.chrome_motox
  data_template:
    title: "Doors!"
    message: "You left an interior door open!"
