################################################################
## packages / fortinet
################################################################

homeassistant:
  customize:
    ################################################
    ## node anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'fortinet'

      fortinet: &fortinet
        <<: *customize
        host: 10.0.0.1

    ################################################
    ## customize / sensor
    ################################################

    sensor.firewall_cpu:
      <<: *customize
      icon: mdi:memory

################################################
## binary_sensors
################################################

################################################
## sensors
################################################

sensor:
  - platform: snmp
    <<: *fortinet
    name: "Firewall CPU"
    unit_of_measurement: "%"
    community: public
    version: 2c
    baseoid: .1.3.6.1.4.1.12356.101.4.1.3.0
    
################################################
## group
################################################

group:
  Fortinet:
    entities:
      - sensor.firewall_cpu
