################################################################
## package / garage
##  Package of garage stuff
################################################################

################################################
## customize
################################################

homeassistant:
  customize:
    ################################################
    ## node anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'garage'

    ################################################
    ## customize / group
    ################################################

    ################################################
    ## customize / light
    ################################################

    ################################################
    ## customize / sensor
    ################################################

    ################################################
    ## customize / cover
    ################################################

    cover.test:
      device_class: garage
      friendly_name: Garage

################################################
## cover
################################################

cover:
  - platform: mqtt
    name: "test"
    state_topic: "cmnd/2/POWER2"
    command_topic: "cmnd/garage_door_opener/POWER1"
    payload_open: "ON"
    payload_close: "ON"
    payload_stop: "ON"
    state_open: "ON"
    state_closed: "OFF"
    optomistic: false
    retain: false

################################################
## group
################################################

    garage_doors:
      name: Garage Doors
      view: no
      control: hidden
      icon: mdi:garage
      entities:
        - cover.test

################################################
## input boolean
################################################

################################################
## sensor
################################################

################################################
## light
################################################

################################################
## binary_sensor
################################################

################################################
## script
################################################
        
################################################
## automation
################################################
