################################################################
## packages / master_bedroom
################################################################

homeassistant:
  customize:
    sensor.master_bedroom_tv_status:
      icon: mdi:television

    sensor.master_bedroom_tv_power:
      icon: mdi:flash

################################################
## sensor
################################################

sensor:
  - platform: mqtt
    state_topic: "smartthings/Master Bedroom TV/power"
    name: "Master Bedroom TV Power"
    unit_of_measurement: "W"
      
  - platform: template
    sensors:
      master_bedroom_tv_status:
        value_template: "{{ states.input_select.master_bedroom_tv_status.state}}"
        friendly_name: "Master Bedroom TV Status"
       
################################################
## switch
################################################

switch:
  - platform: mqtt
    name: "Master Bedroom TV Power Override"
    state_topic: "smartthings/Master Bedroom TV/switch"
    command_topic: "smartthings/Master Bedroom TV/switch"
    payload_on: "on"
    payload_off: "off"
    retain: true

################################################
## input_select
################################################

input_select:
  master_bedroom_tv_status:
    name: "Master Bedroom TV Status"
    options:
      - "On"
      - "Stand-by"
      - "Off"

################################################
## automation
################################################

automation:
  - alias: Set MBR TV status on when power detected
    trigger:
      - platform: numeric_state
        entity_id: sensor.master_bedroom_tv_power
        above: 6
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_bedroom_tv_status
          option: "On"

  - alias: Set MBR TV status stand-by when power betwen 1-6W
    trigger:
      - platform: numeric_state
        entity_id: sensor.master_bedroom_tv_power
        above: 1
        below: 6
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_bedroom_tv_status
          option: "Stand-by"

  - alias: Set MBR TV status off when no power
    trigger:
      - platform: numeric_state
        entity_id: sensor.master_bedroom_tv_power
        below: 1
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_bedroom_tv_status
          option: "Off"

################################################
## scene
################################################

scene:
  - name: Master Bedroom Normal
    entities:
        light.mikes_nightstand:
            state: on
            transition: 2
            brightness_pct: 60
        light.ashleys_nightstand:
            state: on
            transition: 2
            brightness_pct: 60
  - name: Sexy Time
    entities:
        light.mikes_nightstand:
            state: on
            transition: 2
            brightness_pct: 25
        light.ashleys_nightstand:
            state: on
            transition: 2
            brightness_pct: 25
        light.master_bedroom_ceiling_light:
            state: off

################################################
## group
################################################

group:
  Master Bedroom TV:
    entities:
      - sensor.master_bedroom_tv_status
      - sensor.master_bedroom_tv_power
      - switch.master_bedroom_tv_power_override

  Master Bedroom Scenes:
    entities:
      - scene.master_bedroom_normal
      - scene.sexy_time
