################################################################
## packages / master_bedroom
################################################################

homeassistant:
  customize:
    ################################################
    ## node anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'mudroom'

      automation: &automation
        initial_state: true

  #    sensor.master_bedroom_tv_status:
  #      icon: mdi:television
  #
  #    sensor.master_bedroom_tv_power:
  #      icon: mdi:flash

################################################
## sensor
################################################

sensor:
  - platform: mqtt
    <<: *customize
    state_topic: "smartthings/Master Bedroom TV/power"
    name: "Master Bedroom TV Power"
    unit_of_measurement: "W"
       
################################################
## switch
################################################
 
################################################
## light
################################################

light:
  - platform: mqtt
    name: "Master Bedroom Ceiling Light"
    state_topic: "smartthings/Master Bedroom Ceiling Light/switch"
    command_topic: "smartthings/Master Bedroom Ceiling Light/switch"
    payload_on: "on"
    payload_off: "off"
    retain: true

################################################
## input_select
################################################

################################################
## automation
################################################

################################################
## scene
################################################

################################################
## group
################################################

group:
  Master Bedroom TV:
    entities:
      - sensor.master_bedroom_tv_status
      - sensor.master_bedroom_tv_power
      - switch.master_bedroom_tv_power_override
