################################################################
## packages / octoprint
################################################################

homeassistant:
  customize:
    ################################################
    ## node anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'octoprint'

      automation: &automation
        initial_state: true

    switch.3d_printer_power:
      entity_picture: /local/octoprint.png
   


################################################
## binary_sensors
################################################

binary_sensor:
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error

################################################
## sensors
################################################

sensor:
  - platform: octoprint
    name: OctoPrint
    monitored_conditions:
      - Current State
      - Temperatures
      - Job Percentage
        
################################################
## switch
################################################

switch:
  - platform: mqtt
    <<: *customize
    name: "3D Printer Power"
    state_topic: "stat/3d_printer/POWER"
    command_topic: "cmnd/3d_printer/power"
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
    qos: 1

################################################
## rest_command
################################################

rest_command:
  octoprint_connect_printer:
    method: POST
    url: 'http://octoprint.noisufnoc.net/api/connection'
    headers:
      content-type: application/json
      X-Api-Key: !secret octoprint_api_key
    payload: '{"command":"connect", "port":"/dev/ttyACM0", "baudrate":115200}'

################################################
## group
################################################

group:
  OctoPrint:
    entities:
      - switch.3d_printer_power
      - binary_sensor.octoprint_printing
      - binary_sensor.octoprint_printing_error
      - sensor.octoprint_actual_bed_temp
      - sensor.octoprint_actual_tool0_temp
      - sensor.octoprint_current_state
      - sensor.octoprint_job_percentage
      - sensor.octoprint_target_bed_temp
      - sensor.octoprint_target_tool0_temp 
