################################################################
## packages / apcupsd
################################################################

homeassistant:
  customize:

################################################
## binary_sensors
################################################

binary_sensor:
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error

################################################
## sensors
################################################

sensor:
  - platform: octoprint
    name: OctoPrint
    monitored_conditions:
      - Current State
      - Temperatures
      - Job Percentage
        
################################################
## group
################################################

#group:
#  APC UPS Daemon:
#    entities:
#      - binary_sensor.ups_online_status
#      - sensor.ups_status
#      - sensor.ups_battery
#      - sensor.ups_input_voltage
#      - sensor.ups_output_voltage
#      - sensor.ups_load
#      - sensor.ups_time_left
#      - sensor.ups_time_on_battery
#      - sensor.ups_transfer_count
