################################################################
## package / template
##  Template of a package for easy copypasta
################################################################

################################################
## customize
################################################

homeassistant:
  customize:
################################################
## group
################################################

################################################
## input boolean
################################################

################################################
## sensor
################################################

################################################
## input_text
################################################

################################################
## binary_sensor
################################################

################################################
## script
################################################
        
################################################
## automation
################################################

feedreader:
  urls:
    - http://howoldismykid.com/rss/7FABWO4UHXRCZMMSXBNSZCEF5HVCQKR5QUIERSPPRC2JMQ6QA26EVYTO6EPWSUQW
