# Example configuration.yaml entry for the Telegram Bot
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

# Example configuration.yaml entry for the notifier
notify:
  - name: NOTIFIER_NAME
    platform: telegram
    chat_id: !secret telegram_chat_id

################################################
### automation
#################################################

# I borrowed some examples to test with

automation:
  - alias: "Telegram bot that replies the temprature"
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: "/temp"
    action:
      - service: telegram_bot.send_message
        data_template:
          target: '{{ trigger.event.data.user_id }}'
          message: 'The average temprature in the house is currently {{ states.sensor.home_avg_temp.state }}°F'
          disable_notification: True


  - alias: "Telegram bot that replies the weather"
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: "/weather"
    action:
      - service: telegram_bot.send_message
        data_template:
          target: '{{ trigger.event.data.user_id }}'
          message: '{{ states.sensor.dark_sky_hourly_summary.state }}'
          disable_notification: True


  - alias: "Telegram bot args test"
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: '/test'
        args:
          - 'arg'
    action:
      - service: telegram_bot.send_message
        data_template:
          target: '{{ trigger.event.data.user_id }}'
          message: 'You tested the command with an arg!'
          disable_notification: True

  - alias: 'Telegram Ashley is home'
    trigger:
        platform: state
        entity_id: device_tracker.ashley_pixel
        from: not_home
        to: home
    action:
      - service: notify.NOTIFIER_NAME
        data:
          message: "Ashley is home, yay!"
 
  - alias: 'Telegram Mike is home'
    trigger:
        platform: state
        entity_id: device_tracker.mike_taimen
        from: not_home
        to: home
    action:
      - service: notify.NOTIFIER_NAME
        data:
          message: "Mike is home, yay!"

  - alias: 'Telegram Home Assistant Startup Notification'
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: notify.NOTIFIER_NAME
      data:
        message: "Home Assistant Started"

  - alias: 'Telegram Home Assistant Shutdown Notification'
    trigger:
      - platform: homeassistant
        event: shutdown
    action:
      service: notify.NOTIFIER_NAME
      data:
        message: "Home Assistant Shutdown"
