################################################################
## packages / washing_machine
##  Uses power consumption from washing machine sensor
##  to determine if the machine is idle/running/complete
##  door sensor on machine is used to notify if wet clothes
##  are sitting in the drum.
##
##  logic borrowed from https://goo.gl/KhMxn1 @philhawthorne
################################################################

homeassistant:
  customize:

################################################
## input_text
################################################

################################################
## binary_sensors
################################################

binary_sensor:
  - platform: mqtt
    state_topic: "smartthings/Washing Machine Door/contact"
    name: "Washing Machine Door"
    payload_on: "open"
    payload_off: "closed"
    sensor_class: opening

################################################
## sensors
################################################

sensor:
  - platform: mqtt
    state_topic: "smartthings/Washing Machine/power"
    name: "Washing Machine Power"
    unit_of_measurement: "W"

################################################
## input_select
################################################

input_select:
  washing_machine_status:
    name: Washing Machine Status
    options:
      - Idle
      - Running
      - Finishing
      - Clean
    initial: Idle
       
################################################
## group
################################################
       
group:
  washing_machine:
    name: Washing Machine
    entities:
      - sensor.washing_machine_status
      - binary_sensor.washing_machine_door
      - sensor.washing_machine_power
      - switch.washing_machine_power_override

################################################
## switches
################################################
        
switch:
  - platform: mqtt
    name: "Washing Machine Power Override"
    state_topic: "smartthings/Washing Machine/switch"
    command_topic: "smartthings/Washing Machine/switch"
    payload_on: "on"
    payload_off: "off"
    retain: true

################################################
## script
################################################
        
################################################
## automation
################################################

automation:
  - alias: Set washing machine active when power detected
    trigger:
      - platform: numeric_state
        entity_id: sensor.aeotec_smart_energy_switch_power_25_4
        above: 10
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: sensor.washing_machine_status
          state: Idle
        - condition: state
          entity_id: sensor.washing_machine_status
          state: Clean
        - condition: state
          entity_id: sensor.washing_machine_status
          state: Finishing
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Running
   
  - alias: Set washing machine finished when power drops
    trigger:
      - platform: numeric_state
        entity_id: sensor.aeotec_smart_energy_switch_power_25_4
        below: 6
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Running
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Finishing
   
  - alias: Set washing machine clean after timeout
    trigger:
      - platform: state
        entity_id: input_select.washing_machine_status
        to: Finishing
        for:
          minutes: 8
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Finishing
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Clean
   
  - alias: Set washing machine dirty when door opens
    trigger:
      - platform: state
        entity_id: input_select.washingmachine_door_status
        to: 'Open'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Clean
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Idle
