################################################################
## packages / weather
################################################################

homeassistant:
  customize:

################################################
## sensors
################################################

sensor:
  - platform: darksky
    api_key: !secret darksky_api
    monitored_conditions:
      - summary
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - ozone
      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_max
      - temperature_min
      - apparent_temperature_max
      - apparent_temperature_min
      - precip_intensity_max

  - platform: wunderground
    api_key: !secret wunderground_api
    monitored_conditions:
      - alerts
      - dewpoint_c
      - dewpoint_f
      - dewpoint_string
      - feelslike_c
      - feelslike_f
      - feelslike_string
      - heat_index_c
      - heat_index_f
      - heat_index_string
      - elevation
      - location
      - observation_time
      - precip_1hr_in
      - precip_1hr_metric
      - precip_1hr_string
      - precip_today_in
      - precip_today_metric
      - precip_today_string
      - pressure_in
      - pressure_mb
      - pressure_trend
      - relative_humidity
      - station_id
      - solarradiation
      - temperature_string
      - temp_c
      - temp_f
      - UV
      - visibility_km
      - visibility_mi
      - weather
      - wind_degrees
      - wind_dir
      - wind_gust_kph
      - wind_gust_mph
      - wind_kph
      - wind_mph
      - wind_string

################################################
## group
################################################

group:
  weather_sun_clouds:
    name: Sun / Clouds
    entities:
      - sun.sun
      - sensor.dark_sky_summary
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_visibility

  weather_temperature:
    name: Temperature
    entities:
      - sensor.dark_sky_temperature
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_temperature
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_humidity

  weather_report:
    name: Report
    entities:
      - sensor.dark_sky_minutely_summary
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_daily_summary

  weather_wind:
    name: Wind
    entities:
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_bearing

  weather_precipitation:
    name: Precipitation
    entities:
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_nearest_storm_distance
      - sensor.dark_sky_nearest_storm_bearing
      - sensor.dark_sky_pressure
