################################################################
## packages / workwork
##  Uses bayesian binary_sensor to determine if I am working
##  from home at this time.  Apply weight to various sensors
##  to make the decision.
################################################################

homeassistant:
  customize:

################################################
## input_text
################################################

################################################
## binary_sensors
################################################

binary_sensor:
  - platform: 'bayesian'
    name: 'working from home'
    prior: 0.25
    probability_threshold: 0.95
    observations:
      - entity_id: 'sensor.living_room_motion'
        prob_given_true: 0.4
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'off'
      - entity_id: 'sensor.basement_motion'
        prob_given_true: 0.5
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'off'
      - entity_id: 'sensor.bedroom_motion'
        prob_given_true: 0.5
        platform: 'state'
        to_state: 'on'
      - entity_id: 'sensor.sun'
        prob_given_true: 0.7
        platform: 'state'
        to_state: 'below_horizon'

################################################
## sensors
################################################

################################################
## group
################################################

group:
  Working From Home Sensor:
    entities:
      - binary_sensor.working_from_home
       
################################################
## script
################################################
        
################################################
## automation
################################################
