################################################################
## packages / workwork
##  Home Office related devices and sensors
##
##  Uses bayesian binary_sensor to determine if I am working
##  from home at this time.  Apply weight to various sensors
##  to make the decision.
################################################################

homeassistant:
  customize:
    device_tracker.work_mbp_wired:
      hidden: true
    device_tracker.work_mbp_wireless:
      hidden: true
    sensor.work_mbp_online:
      icon: mdi:apple
    binary_sensor.workday_sensor:
      icon: mdi:calendar
    binary_sensor.office_desk_motion_sensor:
      icon: mdi:desktop-classic

################################################
## input_text
################################################

################################################
## binary_sensors
################################################

binary_sensor:
  - platform: 'bayesian'
    name: 'Working From Home'
    prior: 0.25
    probability_threshold: 0.95
    observations:
      - entity_id: 'binary_sensor.office_motion_sensor'
        prob_given_true: 0.4
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'off'
      - entity_id: 'binary_sensor.workday_sensor'
        prob_given_true: 0.4
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'off'
      - entity_id: 'device_tracker.mike_clark'
        prob_given_true: 0.4
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'home'
      - entity_id: 'sensor.work_mbp_online'
        prob_given_true: 0.5
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'online'
      - entity_id: 'binary_sensor.office_door'
        prob_given_true: 0.5
        platform: 'state'
        to_state: 'on'
      - entity_id: 'binary_sensor.office_desk_motion_sensor'
        prob_given_true: 0.7
        platform: 'state'
        to_state: 'on'

  - platform: workday
    country: US
    province: OH

################################################
## sensors
################################################

sensor:
  - platform: template
    sensors:
      work_mbp_online:
        friendly_name: 'Work Macbook Online'
        value_template: >-
            {%- if is_state("device_tracker.work_mbp_wired", "home") %}
                online
            {% elif is_state("device_tracker.work_mbp_wireless", "home") %}
                online
            {% else %}
                offline
            {%- endif %}

################################################
## group
################################################

group:
  Working From Home Sensor:
    entities:
      - binary_sensor.working_from_home
      - device_tracker.mike_clark
      - sensor.work_mbp_online
      - binary_sensor.office_door
      - binary_sensor.office_desk_motion_sensor
      - binary_sensor.office_motion_sensor
      - binary_sensor.workday_sensor
       
################################################
## script
################################################
        
################################################
## automation
################################################
